services:
  web:
    build: .
    volumes:
      - static_volume:/app/staticfiles
    env_file: .env
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      # Use the PORT variable from .env, or default to 80 if missing
      - "${NGINX_HTTP_PORT:-80}:80"
      # Use the HTTPS_PORT variable, or default to 443
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      # Dynamically pick the config file based on the environment
      - ./${NGINX_CONF_FILE:-nginx/default.conf}:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      # These volumes will simply be empty/ignored locally if the folders don't exist
      - /etc/letsencrypt:/etc/letsencrypt:ro  
      - ./certbot/www:/var/www/certbot        
    depends_on:
      - web

volumes:
  static_volume:
